services:
  - type: web
    name: student-task-manager-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
